export const SET_CENTER_MAP_LOCATION = 'SET_CENTER_MAP_LOCATION'
export const SET_PIN_LOCATION = 'SET_PIN_LOCATION'
export const CHANGE_MAP_MODE = 'CHANGE_MAP_MODE'
export const GET_USER_LOCATION_STARTED = 'GET_USER_LOCATION_STARTED'
export const GET_USER_LOCATION_SUCCESS = 'GET_USER_LOCATION_SUCCESS'
export const GET_USER_LOCATION_FAILURE = 'GET_USER_LOCATION_FAILURE'

export const mapModes = {
  HIDDEN: 'HIDDEN',
  RESTAURANTS: 'RESTAURANTS',
  PICKING: 'PICKING'
}
