//Map
export const SET_CENTER_MAP_LOCATION = 'SET_CENTER_MAP_LOCATION'
export const SET_PIN_LOCATION = 'SET_PIN_LOCATION'
export const CHANGE_MAP_MODE = 'CHANGE_MAP_MODE'
export const GET_USER_LOCATION_STARTED = 'GET_USER_LOCATION_STARTED'
export const GET_USER_LOCATION_SUCCESS = 'GET_USER_LOCATION_SUCCESS'
export const GET_USER_LOCATION_FAILURE = 'GET_USER_LOCATION_FAILURE'


//Notification
export const SET_NOTIFICATION = 'SET_NOTIFICATION'
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION'


//Popup
export const OPEN_POPUP = 'OPEN_POPUP'
export const CLOSE_POPUP = 'CLOSE_POPUP'


//Restaurant
export const GET_RESTAURANTS_STARTED = 'GET_RESTAURANTS_STARTED'
export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS'
export const GET_RESTAURANTS_FAILURE = 'GET_RESTAURANTS_FAILURE'
export const ADD_RESTAURANT_STARTED = 'ADD_RESTAURANT_STARTED'
export const ADD_RESTAURANT_SUCCESS = 'ADD_RESTAURANT_SUCCESS'
export const ADD_RESTAURANT_FAILURE = 'ADD_RESTAURANT_FAILURE'
export const UPDATE_RESTAURANT_STARTED = 'UPDATE_RESTAURANT_STARTED'
export const UPDATE_RESTAURANT_SUCCESS = 'UPDATE_RESTAURANT_SUCCESS'
export const UPDATE_RESTAURANT_FAILURE = 'UPDATE_RESTAURANT_FAILURE'
export const DENOUNCE_RESTAURANT_STARTED = 'DENOUNCE_RESTAURANT_STARTED'
export const DENOUNCE_RESTAURANT_SUCCESS = 'DENOUNCE_RESTAURANT_SUCCESS'
export const DENOUNCE_RESTAURANT_FAILURE = 'DENOUNCE_RESTAURANT_FAILURE'
export const LIKING_STARTED = 'LIKING_STARTED'
export const ADD_LIKE = 'ADD_LIKE'
export const REMOVE_LIKE = 'REMOVE_LIKE'
export const LIKING_FINISHED = 'LIKING_FINISHED'
export const CHANGE_SELECTED_RESTAURANT = 'CHANGE_SELECTED_RESTAURANT'
export const SET_SUCCESS_NOTIFICATION = 'SET_SUCCESS_NOTIFICATION'
export const SET_ERROR_NOTIFICATION = 'SET_ERROR_NOTIFICATION'
export const DISMISS_RESTAURANT_ERROR = 'DISMISS_RESTAURANT_ERROR'
export const DISMISS_RESTAURANT_SUCCESS = 'DISMISS_RESTAURANT_SUCCESS'


//System
export const SET_CONNECTION_STATE = 'SET_CONNECTION_STATE'
export const SET_SW_EXISTENCE = 'SET_SW_EXISTENCE'


//User
export const SET_USER = 'SET_USER'