function getAllFoods() {
  const values = Object.values(foodTable)
  const allFoods = new Set(values)
  return Array.from(allFoods)
}

const foodTable = {
  escondidinho: 'escondidinho',
  salada: 'salada',
  saladas: 'saladas',
  bolinho: 'bolinho',
  brownie: 'brownie',
  brunch: 'brunch',
  burrito: 'burrito',
  charlote: 'charlote',
  chilli: 'chilli',
  chips: 'chips',
  chocolate: 'chocolate',
  chocolates: 'chocolate',
  chocolatequente: 'chocolate quente',
  congelado: 'congelados',
  congelados: 'congelados',
  cookie: 'cookie',
  cookies: 'cookies', 
  dahl: 'dahl',
  empanada: 'empanada',
  empanadas: 'empanada',
  guacamole: 'guacamole',
  lamen: 'lámen',
  ramen: 'lámen',
  nacho: 'nachos',
  nachos: 'nachos',
  nasigoreng: 'nasi goreng',
  nhoque: 'nhoque',
  oleaginosas: 'oleaginosas',
  ovodechocolate: 'ovo de chocolate',
  padthai: 'pad thai',
  poke: 'poke',
  rolinhoprimavera: 'rolinho primavera',
  sapparot: 'sapparot',
  semgluten: 'sem glúten' ,
  sezame: 'sezame',
  talharim: 'talharim',
  tofu: 'tofu',
  trufa: ' trufa',
  vitamina: 'vitamina',
  waffle: 'waffle',
  yakisoba: 'yakissoba',
  moussaca: 'moussaca',
  bureca: 'bureca',
  acaraje: 'acarajé',
  almoco: 'almoço',
  almocos: 'almoço',
  bemcasado: 'bem casado',
  biscoito: 'biscoito',
  biscoitos: 'biscoito',
  bolo: 'bolo',
  bolos: 'bolo',
  bufe: 'buffet',
  buffet: 'buffet',
  cafecolonial: 'café colonial',
  caldodecana: 'caldo de cana',
  cha: 'chá',
  chas: 'chás',
  churrasco: ' veg churrasco',
  churros: 'churros',
  coxinha: 'coxinha',
  coxinhas: 'coxinha',
  docedeleite: 'doce de leite vegetal',
  docedeleitevegetal: 'doce de leite vegetal',
  empada: 'empada',
  empadas: 'empada',
  espetinho: 'espetinho',
  estrogonofe: 'estrogonofe',
  strogonof: 'estrogonofe',
  strogonoff: 'estrogonofe',
  farofa: 'farofa',
  feijoada: 'feijoada',
  geleia: 'geléia',
  geleias: 'geléia',
  granola: 'granola',
  honeycomb: 'honeycomb',
  kilo: 'buffet',
  leitecondensadovegetal: 'leite condensado vegetal',
  leitevegetal: 'leite vegetal',
  maionese: 'maionese',
  saladadebatata: 'salada de batata',
  mandioca: 'mandioca',
  aipim: 'mandioca',
  manjar: 'manjar',
  moqueca: 'moqueca',
  ovo: 'ovo',
  crepioca: 'crepioca',
  pacoca: 'paçoca',
  paletamexicana: 'paleta mexicana',
  palhaitaliana: 'palha italiana',
  paodemel: 'pão de mel',
  paodemelado: 'pão de melado',
  paodequeijo: 'pão de queijo',
  paodebeijo: 'pão de beijo',
  naodequeijo: 'não de queijo',
  pastel: 'pastel',
  pedemoleque: 'pé de moleque',
  pf: 'prato feito',
  picole: 'picolé',
  picoles: 'picolé',
  pinhao: 'pinhão',
  pratofeito: 'prato feito',
  pudim: 'pudim',
  rocambole: 'rocambole',
  saladadefruta: 'salada de fruta',
  sanduiche:  'sanduíche',
  sanduiches: 'sanduíche',
  sandwiches: 'sanduíche',
  snacks: 'snacks',
  snack: 'snacks',
  sonho: 'sonho',
  sopa: 'sopa',
  sopas: 'sopa',
  sorvete: 'sorvete',
  sorvetes: 'sorvete' ,
  suco: 'suco',
  sucos: 'suco',
  tapioca: 'tapioca',
  tapiocas: 'tapioca',
  torta: 'torta',
  tortas: 'torta',
  babaghanoush: 'baba ghanoush',
  burma: 'burma',
  cafta: 'cafta',
  kafta: 'cafta',
  dolma:  'dolma',
  esfiha:  'esfiha',
  falafel:  'faláfel',
  fatoush:  'fatoush',
  halva: 'halva',
  homus: 'homus',
  kibe: 'kibe',
  quibe: 'kibe',
  pita: 'pão pita',
  paopita: 'pão pita',
  shawarma: 'shawarma',
  tabule:  'tabule',
  tahine: 'tahine',
  aligot: 'aligot',
  batatafrita: 'batata frita',
  bomba: 'bomba', 
  brioche: 'brioche',
  carolina: 'carolina',
  cassoulet: 'cassoulet',
  ceviche: 'ceviche',
  cheesecake: 'cheesecake',
  cremebrulee: 'crème brûlée',
  crepe: 'crepe',
  croissant: 'croissant',
  folhado: 'folhado',
  fondue: 'fondue',
  fricasse: 'fricassê',
  macarons: 'macarons',
  madeleine: 'madeleine',
  milfolhas: 'mil folhas',
  moelleux: 'moelleux',
  mousse: 'mousse',
  musse: 'mousse',
  omelete: 'omelete',
  omeletdufromage: 'omelete' ,
  panquecas: 'panquecas',
  pavlova: 'pavlova',
  petitgateau: 'petit gâteau',
  polpeta: 'polpeta',
  profiterole: 'profiterole',
  quiche: 'quiche',
  ratatouille: 'ratatouille',
  raviolí: 'raviolí',
  soufflé: 'soufflé',
  tartar: 'tartar',
  tartare: 'tartare',
  trifle: 'trifle',
  verrine: 'verrine',
  almondega: 'almôndega',
  arancini: 'arancini',
  bolinhodearroz: 'bolinho de arroz',
  carpacio: 'carpacios',
  ciabatta: 'ciabatta',
  caponata: 'caponata',
  compota: 'compota',
  expresso: 'café',
  gelato: 'gelato',
  lasanha: 'lasanha',
  lasagna: 'lasanha',
  massa: 'massa',
  panetone: 'panetone',
  pannacotta: 'panna cotta',
  pesto: 'pesto',
  risoto: 'risoto',
  sodaitaliana: 'soda italiana',
  sorbet: 'sorbet',
  spaghetti: 'espaguete',
  espaguete: 'espaguete',
  tiramisu: 'tiramisú',
  burguer: 'búrguer',
  xburguer: 'búrguer',
  xisburguer: 'búrguer',
  burger: 'búrguer',
  burgers: 'búrguer',
  hamburguer: 'búrguer',
  hamburguers: 'búrguer',
  hamburgueres: 'búrguer',
  hamburger: 'búrguer',
  hamburgers: 'búrguer',
  pizza: 'pizza',
  pizzas: 'pizza',
  hotdog: 'hotdog',
  hotdogs: 'hotdog',
  cachorroquente: 'hotdog',
  cachorrosquentes: 'hotdog',
  cachorrosquente: 'hotdog',
  cachorroquentes: 'hotdog',
  porcao: 'porções',
  porcaos: 'porções',
  porcoes: 'porções',
  drink: 'drinks',
  drinks: 'drinks',
  bebida: 'drinks',
  bebidas: 'drinks',
  cafe: 'café',
  cafes: 'café',
  salgado: 'salgados',
  salgados: 'salgados',
  doce: 'doces',
  doces: 'doces',
  sushi: 'sushi',
  sushis: 'sushi',
  brasileiro: 'brasileiro',
  brasileira: 'brasileiro',
  mexicano: 'mexicano',
  mexicana: 'mexicano',
  italiano: 'italiano',
  italiana: 'italiano',
  arabe: 'árabe',
  chines: 'chinês',
  chinesa: 'chinês',
  japones: 'japonês',
  japonesa: 'japonês'      
}

module.exports = { getAllFoods, foodTable }